server:
  port: 8090

#dubbo:
#  # 配置服务信息
#  application:
#    name: other-gateway
#    # 禁用QOS同一台机器可能会有端口冲突现象
#    qos-enable: false
#    qos-accept-foreign-ip: false
#  # 配置注册中心
#  registry:
#    address: nacos://172.16.0.18:8848
#  # 设置协议-协议由提供方指定消费方被动接受
#  protocol:
#    name: dubbo
#    port: -1
#    # 设置超时时间
#  consumer:
#    timeout: 4000
#    check: false

spring:
  application:
    name: other-gateway
  redis:
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    #连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接超时时间（毫秒）
    timeout: 5000

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      routes:
        #####################
        # 其他模块 #
        #####################

        #time
        #包含需要token的路径
        - id: time
          uri: http://192.168.0.13:8080/
          predicates:
            - Path=/shops/{did}/advertisement/timesegments, /shops/{did}/flashsale/timesegments, /shops/{did}/advertisement/timesegments/{id}, /shops/{did}/flashsale/timesegments/{id}
          filters:
            - PrefixPath=/time
            - Auth=authorization
        #favorites
        #包含需要token的路径
        - id: favorites
          uri: http://192.168.0.13:8088/
          predicates:
            - Path=/favorites, /favorites/goods/{skuId}, /favorites/{id}
          filters:
            - PrefixPath=/favorite
            - Auth=authorization

        #advertisement
        #包含需要token的路径
        - id: ad
          uri: http://192.168.0.13:8081/
          predicates:
            - Path=/shops/{did}/advertisement/{id}, /shops/{did}/advertisement/{id}/**,/shops/{did}/timesegments/{id}/advertisement,/shops/{did}/timesegments/{id}/advertisement/**
          filters:
            - PrefixPath=/advertise
            - Auth=authorization
        #包含不需要token的路径
        - id: ad-nonAuth
          uri: http://192.168.0.13:8081/
          predicates:
            - Path=/advertisement/states, /advertisement/current
          filters:
            - PrefixPath=/advertise

        #user
        #包含不需要token的路径
        - id: users-nonAuth
          uri: http://192.168.0.17:8080/
          predicates:
            - Path=/users/states, /users/login, /users/password/**
          filters:
            - PrefixPath=/user

        - id: users-nonAuth2
          uri: http://192.168.0.17:8080/
          predicates:
            - Path=/users
            - Method=POST
          filters:
            - PrefixPath=/user
        #包含需要token的路径
        - id: users
          uri: http://192.168.0.17:8080/
          predicates:
            - Path=/users/all, users/logout, /users/{id}, /users
          filters:
            - PrefixPath=/user
            - Auth=authorization

        #shoppingCart
        #包含需要token的路径
        - id: shoppingCart
          uri: http://192.168.0.17:8088/
          predicates:
            - Path=/carts,/carts/{id}
          filters:
            - PrefixPath=/cart
            - Auth=authorization

        #AfterSale
        #包含不需要token的路径
        - id: aftersale-nonAuth
          uri: http://192.168.0.20:8081/
          predicates:
            - Path=/aftersales/states
          filters:
            - PrefixPath=/aftersale
        #包含需要token的路径
        - id: aftersale
          uri: http://192.168.0.20:8081/
          predicates:
            - Path=/aftersales/{id}/**,/orderitems/{id}/aftersales,/aftersales
          filters:
            - PrefixPath=/aftersale
            - Auth=authorization

        #Address
        #包含需要token的路径
        - id: address
          uri: http://192.168.0.20:8083/
          predicates:
            - Path=/addresses/**,/addresses,/region/{id}/ancestor,/shops/{did}/regions/**
          filters:
            - PrefixPath=/address
            - Auth=authorization

        #share
        #包含不需要token的路径
        - id: share-nonAuth
          uri: http://192.168.0.16:8080/
          predicates:
            - Path=/shareactivities
          filters:
            - PrefixPath=/share
        #包含需要token的路径
        - id: share
          uri: http://192.168.0.16:8080/
          predicates:
            - Path=/skus/{id}/shares, /shares, /shops/{did}/skus/{id}/shares, /beshared, /shops/{did}/skus/{id}/beshared, /shops/{shopId}/skus/{id}/shareactivities, /shops/{shopId}/shareactivities/{id}, /shops/{shopId}/shareactivities/{id}/online
          filters:
            - PrefixPath=/share
            - Auth=authorization

        #footprint
        #包含需要token的路径
        - id: footprint
          uri: http://192.168.0.16:8081/
          predicates:
            - Path=/shops/{did}/footprints
          filters:
            - PrefixPath=/footprint
            - Auth=authorization


            #####################
            # 订单模块 #
        #####################

        - id: order
          uri: http://localhost:8086/
          predicates:
            - Path=/orders,/orders/states,/orders/{id},/orders/{id}/confirm,/shops/{shopId}/orders,/shops/{shopId}/orders/{id},/shops/{shopId}/orders/{id}/deliver
          filters:
            - PrefixPath=/order
            - Auth=authorization
        - id: freight
          uri: http://localhost:8083/
          predicates:
            - Path=/region/{rid}/price,/shops/{id}/freightmodels,/shops/{shopId}/freightmodels/{id}/**,/shops/{shopId}/weightItems/**,/shops/{shopId}/pieceItems/**
          filters:
            - PrefixPath=/freight
            - Auth=authorization
        - id: payment
          uri: http://localhost:8085/
          predicates:
            - Path=/payments/**,/orders/{id}/payments,/shops/{shopId}/orders/{id}/payments,/aftersales/{id}/**,/shops/{shopId}/aftersales/{id}/**,/shops/{shopId}/payments/{id}/**,/shops/{shopId}/orders/{id}/refunds,/orders/{id}/refunds,/aftersales/{id}/refunds
          filters:
            - PrefixPath=/payment
            - Auth=authorization

            #####################
            # 商品模块 #
            #####################
        #包含不需要token的
        - id: goods-nonAuth
          uri: http://192.168.0.19:8084/
          predicates:
            - Path=/skus/states, /skus, /skus/{id}, /categories/**, /spus/{id}, /brands
          filters:
            - PrefixPath=/goods
        #包含需要token的路径
        - id: goods
          uri: http://192.168.0.19:8084/
          predicates:
            - Path=/categories/{id}/subcategories, /share/**
          filters:
            - PrefixPath=/goods
            - Auth=authorization

        #包含不需要token的路径
        - id: flashsale-nonAuth
          uri: http://192.168.0.12:8090/
          predicates:
            - Path=/timesegments/{id}/flashsales, /flashsales/current
          filters:
            - PrefixPath=/flashsale

        #包含不需要token的路径
        - id: comment-nonAuth
          uri: http://192.168.0.11:8088/
          predicates:
            - Path=/comments/states, /skus/{id}/comments
          filters:
            - PrefixPath=/comment
        #包含需要token的路径
        - id: comment
          uri: http://192.168.0.11:8088/
          predicates:
            - Path=/comments, /orderitems/{id}/comments
          filters:
            - PrefixPath=/comment
            - Auth=authorization

        #包含不需要token的路径
        - id: coupon-nonAuth
          uri: http://192.168.0.12:8091/
          predicates:
            - Path=/couponactivities, /couponactivities/{id}/skus, /coupons/states
          filters:
            - PrefixPath=/coupon
        #包含需要token的路径
        - id: coupon
          uri: http://192.168.0.12:8091/
          predicates:
            - Path=/coupons, /couponactivities/{id}/usercoupons
          filters:
            - PrefixPath=/coupon
            - Auth=authorization

        #包含不需要token的路径
        - id: presale-nonAuth
          uri: http://192.168.0.11:8087/
          predicates:
            - Path=/presales/**,
          filters:
            - PrefixPath=/presale

        #包含不需要token的路径
        - id: groupon-nonAuth
          uri: http://192.168.0.19:8086/
          predicates:
            - Path=/groupons/states
          filters:
            - PrefixPath=/groupon
        #包含需要token的路径
        - id: groupon
          uri: http://192.168.0.19:8086/
          predicates:
            - Path=/groupons
          filters:
            - PrefixPath=/groupon
            - Auth=authorization

        #包含不需要token的路径
        - id: shop-nonAuth
          uri: http://192.168.0.19:8084/
          predicates:
            - Path=/shops/states
          filters:
            - PrefixPath=/shop
        #包含需要token的路径
        - id: shop
          uri: http://192.168.0.19:8084/
          predicates:
            - Path=/shops, /shops/{id}, /shops/{id}/onshelves, /shops/{id}/offshelves, /shops/{shopId}/newshops/{id}/audit
          filters:
            - PrefixPath=/shop
            - Auth=authorization


management:
  endpoint:
    gateway:
      enabled: true

## 配置rocketmq
#rocketmq:
#  # 指定namesrv地址
#  name-server: 47.115.162.144:9876
#  producer:
#    #生产者group名称
#    group: producer_group
#    #一次发送多少数量消息
#    max-message-size: 4096
#    #发送消息超时时间,默认3000
#    send-message-timeout: 3000
#    #发送消息失败重试次数，默认2
#    retry-times-when-send-async-failed: 2
#
## 网关token相关配置
gateway:
  jwtExpire: 3600
  refreshJwtTime: 60

